# Generated by Django 5.0.2 on 2024-04-22 18:59

import django.db.models.deletion
import mptt.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Enter the question.', max_length=500, verbose_name='Question Text')),
                ('complexity', models.CharField(choices=[('1', 'Easy'), ('2', 'Medium'), ('3', 'Hard')], default='1', max_length=20)),
                ('type', models.CharField(choices=[('1', 'Easy'), ('2', 'Medium'), ('3', 'Hard')], default='1', max_length=20)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['quiz'],
            },
        ),
        migrations.CreateModel(
            name='ChoiceAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Answer Text')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Is Correct?')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.question')),
            ],
            options={
                'verbose_name': 'Choice Answer',
                'verbose_name_plural': 'Choice Answers',
                'ordering': ['question'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable='True', help_text='Enter the name of the quiz.', max_length=50, verbose_name='Name')),
                ('slug', models.SlugField(help_text='A unique slug for the quiz.', max_length=255, unique=True, verbose_name='URL')),
                ('short_description', models.TextField(blank=True, help_text='Enter a short description of the quiz.', max_length='100', null=True, verbose_name='Short Description')),
                ('description', models.TextField(blank=True, help_text='Enter a description of the quiz.', max_length='1000', null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='Edited at')),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(help_text='Choose a quiz this question belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the topic.', max_length=255, verbose_name='Name')),
                ('image', models.ImageField(blank=True, help_text='Upload an image for the category.', null=True, upload_to='quiz/topic/', verbose_name='Image')),
                ('slug', models.SlugField(help_text='A unique slug for the topic.', max_length=255, unique=True, verbose_name='URL')),
                ('short_description', models.TextField(blank=True, help_text='Enter a short description of the topic.', max_length='100', null=True, verbose_name='Short Description')),
                ('description', models.TextField(blank=True, help_text='Enter a description of the topic.', max_length='1000', null=True, verbose_name='Description')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='quiz.topic', verbose_name='Parent Topic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='Choose the topic of the quiz.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='quiz.topic', verbose_name='Topic'),
        ),
    ]
