# Generated by Django 5.0.2 on 2024-04-23 11:57

import django.db.models.deletion
import mptt.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_question_complexity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['created_at'], 'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterField(
            model_name='choiceanswer',
            name='is_correct',
            field=models.BooleanField(default=False, help_text='Mark if this answer is correct or incorrect.', verbose_name='Is Correct?'),
        ),
        migrations.AlterField(
            model_name='choiceanswer',
            name='question',
            field=models.ForeignKey(help_text='Choose the question this answer belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.question'),
        ),
        migrations.AlterField(
            model_name='choiceanswer',
            name='text',
            field=models.CharField(help_text='Enter the answer text.', max_length=255, verbose_name='Answer Text'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='author',
            field=models.ForeignKey(default=None, help_text='The author of the quiz.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when the quiz was created.', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='edited_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time when the quiz was last edited.', verbose_name='Edited at'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the quiz.', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the topic.', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='The parent topic if this topic is a sub-topic.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='quiz.topic'),
        ),
    ]
