# Generated by Django 5.0.2 on 2024-04-23 12:04

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_quiz_options_alter_choiceanswer_is_correct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choiceanswer',
            name='question',
            field=models.ForeignKey(help_text='Choose the question this answer belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='complexity',
            field=models.CharField(choices=[('1', 'Easy'), ('2', 'Medium'), ('3', 'Hard')], default='1', help_text='Choose the question complexity from 1 to 3.', max_length=20, verbose_name='Complexity'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(help_text='Choose a quiz this question belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz', verbose_name='Quiz'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='The parent topic if this topic is a sub-topic.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='quiz.topic', verbose_name='Parent Topic'),
        ),
    ]
