# Generated by Django 5.0.2 on 2024-05-02 20:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_quiz_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='completions',
        ),
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(help_text='Completion percentage.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Percentage')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the completion was made.', verbose_name='Created at')),
                ('quiz', models.ForeignKey(help_text='The quiz being completed.', on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='quiz.quiz', verbose_name='Quiz')),
                ('user', models.ForeignKey(help_text='The user who the completion belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='quiz_completions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Completion',
                'verbose_name_plural': 'Completions',
                'db_table_comment': 'Quiz completions.',
                'ordering': ['quiz'],
            },
        ),
        migrations.CreateModel(
            name='PickedAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(help_text='The answer that was picked.', on_delete=django.db.models.deletion.CASCADE, to='quiz.choiceanswer', verbose_name='Answer')),
                ('completion', models.ForeignKey(help_text='The completion instance that this answer was picked in.', on_delete=django.db.models.deletion.CASCADE, to='quiz.completion', verbose_name='Completion')),
            ],
            options={
                'verbose_name': 'Picked answer',
                'verbose_name_plural': 'Picked answers',
                'db_table_comment': 'A picked answer in a completion.',
                'ordering': ['completion'],
            },
        ),
        migrations.AddField(
            model_name='completion',
            name='picked_answers',
            field=models.ManyToManyField(help_text='Answers that user picked from quiz questions.', related_name='completions', through='quiz.PickedAnswer', to='quiz.choiceanswer', verbose_name='Picked Answers'),
        ),
    ]
