# Generated by Django 5.0.2 on 2024-05-02 20:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_remove_quiz_completions_completion_pickedanswer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='completion',
            unique_together={('user', 'quiz')},
        ),
    ]
