# Generated by Django 5.0.2 on 2024-05-03 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_alter_completion_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='topic',
            field=models.ForeignKey(help_text='Choose the topic of the quiz.', on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='quiz.topic', verbose_name='Topic'),
        ),
    ]
