# Generated by Django 5.0.2 on 2024-05-07 22:09

import apps.quiz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_alter_quiz_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for the category.', null=True, upload_to=apps.quiz.models.generate_image_filename, verbose_name='Image'),
        ),
    ]
