# Generated by Django 5.0.2 on 2024-03-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='article_images', verbose_name='Image'),
        ),
    ]
