# Generated by Django 5.0.2 on 2024-03-04 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='dislikes',
            field=models.IntegerField(auto_created=True, default=0, editable=False, verbose_name='Dislikes'),
        ),
    ]
