# Generated by Django 5.0.2 on 2024-04-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at', 'id'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, help_text='Enter the content of the article.', max_length=1000, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='dislikes',
            field=models.PositiveIntegerField(auto_created=True, default=0, editable=False, verbose_name='Dislikes'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(help_text='Upload an image for the article.', upload_to='article_images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.PositiveIntegerField(auto_created=True, default=0, editable=False, verbose_name='Likes'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='Enter a title for the article.', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(help_text='Enter the content of the comment.', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.PositiveIntegerField(auto_created=True, default=0, editable=False, verbose_name='Likes'),
        ),
    ]
