# Generated by Django 5.0.2 on 2024-04-18 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_article_options_alter_article_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-likes', '-created_at'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelTableComment(
            name='comment',
            table_comment='Article comments',
        ),
    ]
