# Generated by Django 5.0.2 on 2024-04-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_comment_options_alter_comment_table_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, help_text='Enter the content of the article.', max_length=10000, verbose_name='Content'),
        ),
    ]
