# Generated by Django 5.0.2 on 2024-04-27 19:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('catalog', '0008_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('user', models.OneToOneField(help_text='User this cart belongs to.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when cart was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Time when cart was last updated.', verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'ordering': ['updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of the product in its cart.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('cart', models.ForeignKey(help_text='The cart associated with this instance.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='order.cart', verbose_name='Cart')),
                ('product', models.ForeignKey(help_text='The product assosiated with this instance.', on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Cart product',
                'verbose_name_plural': 'Cart products',
                'ordering': ['cart', 'product'],
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
