# Generated by Django 5.0.2 on 2024-04-22 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0008_alter_productcategory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Amount of product.', verbose_name='Кількість')),
                ('product', models.ForeignKey(help_text='Cart product.', on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Product')),
                ('user', models.ForeignKey(help_text='Owner of the cart.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'ordering': ('id',),
                'unique_together': {('user', 'product')},
            },
        ),
    ]
