# Generated by Django 5.0.2 on 2024-04-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Quantity of product.', verbose_name='Quantity'),
        ),
    ]
