# Generated by Django 5.0.2 on 2024-04-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_catalog_description_alter_catalog_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a description for the category.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for the category.', null=True, upload_to='catalog/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='name',
            field=models.CharField(help_text='Enter the name of the category.', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='slug',
            field=models.SlugField(help_text='A unique slug for the category.', max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
