# Generated by Django 5.0.2 on 2024-04-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_productcategory_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for the product.', null=True, upload_to='catalog/product/', verbose_name='Image'),
        ),
    ]
