# Generated by Django 5.0.2 on 2024-04-19 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['price', 'quantity'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
